Dylan Ross

Create a combined table (a `polars.DataFrame`) with all metadata and -omics data pre-processed, cleaned, and aligned by sample ID. This will make it super convenient to query out tables for my various data analysis needs.

## Setup

### Imports

In [1]:
import sys
import os 

# necessary to make data loading functions available
# Jupyter server should be running from src/python
sys.path.append(
    os.getcwd()
)

In [2]:
from pilot.data_import import (
    import_acetyl,
    import_global,
    import_lipids,
    import_meta,
    import_metabolites,
    import_phospho,
    import_rna,
    syn_login
)

In [3]:
from collections import defaultdict

import polars as pl
import pandas as pd

### Synapse login token/session

In [4]:
SYN = syn_login()

Welcome, dylan.ross!

### Constants

In [5]:
# Jupyter server should be running from src/python
CACHE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.getcwd())),
    "analysis",
    "dylan",
    "_cache"
)

# metadata and combined -omics data saved to Apache arrow files
# for quick and easy loading
META_CACHE = os.path.join(CACHE_DIR, "meta.arrow")
COMBINED_CACHE = os.path.join(CACHE_DIR, "combined.arrow")

## Load Metadata and Each -Omics Dataset separately
### Metadata

In [6]:
meta = (
    pl.from_pandas(
        import_meta(SYN), 
        include_index=True
    )
    .rename({"None": "Sample"})
    # keep only a subset of the mutation data:
    # important mutations from Eisfeld paper
    # https://doi.org/10.1038/s41588-024-01929-x
    .select(
        "Sample",
        "Age",
        "Sex",
        "Race",
        "Study", 
        # for all of the mutation data, (implicit) treat "Not measured" as "WT"
        # convert the column into boolean indicating mutation state
        (pl.col("FLT3_ITD") == "Mutant"),
        # condense IDH1 and IDH2 into single IDH1 & IDH2 category
        (
            (pl.col("IDH1") == "Mutant")
            & (pl.col("IDH2") == "Mutant")
        ).alias("IDH1+IDH2"),
        (pl.col("NPM1") == "Mutant"),
        (pl.col("NRAS") == "Mutant"),
    )
    # retain only samples with "White" or "Black" race label
    .filter(pl.col("Race").is_in(["White", "Black"]))
)
meta

Downloading files: 100%|██████████████████████████████████████████████████████████████| 791k/791k [00:00<00:00, 899kB/s, syn69692583]

[syn69692583]: Downloaded to /Users/dylan.ross/.synapseCache/115/169939115/combinedBeatAML_pilotMetadata_20260317.csv

Downloading files: 100%|██████████████████████████████████████████████████████████████| 791k/791k [00:00<00:00, 896kB/s, syn69692583]

[syn64126463:beataml_waves1to4_sample_mapping.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/872/150013872/beataml_waves1to4_sample_mapping.xlsx, skipping download.
[syn64126458:1-s2.0-S1535610822003129-mmc2.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/845/150013845/1-s2.0-S1535610822003129-mmc2.xlsx, skipping download.

shape: (284, 9)
┌─────────────────┬──────┬────────┬───────┬───┬──────────┬───────────┬───────┬───────┐
│ Sample          ┆ Age  ┆ Sex    ┆ Race  ┆ … ┆ FLT3_ITD ┆ IDH1+IDH2 ┆ NPM1  ┆ NRAS  │
│ ---             ┆ ---  ┆ ---    ┆ ---   ┆   ┆ ---      ┆ ---       ┆ ---   ┆ ---   │
│ str             ┆ f64  ┆ str    ┆ str   ┆   ┆ bool     ┆ bool      ┆ bool  ┆ bool  │
╞═════════════════╪══════╪════════╪═══════╪═══╪══════════╪═══════════╪═══════╪═══════╡
│ 11-00261        ┆ 74.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ false ┆ false │
│ 11-00503        ┆ 54.0 ┆ Female ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ 11-00475        ┆ 65.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ 12-00032        ┆ 70.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ false ┆ false │
│ 11-00376        ┆ 49.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ …               ┆ …    ┆ …      ┆ …     ┆ … ┆ …        ┆ …         ┆ …     ┆ …     │
│ 16-01109-Bridge ┆ 33.0 ┆ Male   ┆ Black ┆ … ┆ false    ┆ false     ┆ false ┆ false │
│ 16-01191-Bridge ┆ 65.0 ┆ Female ┆ White ┆ … ┆ false    ┆ false     ┆ false ┆ true  │
│ 17-00025-Bridge ┆ 39.0 ┆ Female ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ 17-00741-Bridge ┆ 20.0 ┆ Male   ┆ White ┆ … ┆ false    ┆ false     ┆ true  ┆ true  │
│ 17-00881-Bridge ┆ 76.0 ┆ Female ┆ White ┆ … ┆ false    ┆ false     ┆ false ┆ false │
└─────────────────┴──────┴────────┴───────┴───┴──────────┴───────────┴───────┴───────┘

### Acetylomics

In [7]:
acetyl = (
    (_df := 
        pl.from_pandas(
            import_acetyl(SYN), 
            include_index=True
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Acetylomics").alias("Block"),
        pl.exclude("Block")
    )
)
acetyl

[syn69075568:ptrc_ex26_crosstab_acetyl_siteid_corrected.txt]: Found existing file at /Users/dylan.ross/.synapseCache/514/161922514/ptrc_ex26_crosstab_acetyl_siteid_corrected.txt, skipping download.
[syn25807733:Ex10_metadata.txt]: Found existing file at /Users/dylan.ross/.synapseCache/668/78060668/Ex10_metadata.txt, skipping download.
[syn68835814:PTRC_Exp26 Sample Key.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/432/161070432/PTRC_Exp26 Sample Key.xlsx, skipping download.

shape: (3_285, 100)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ PS88-0050 ┆ PS88-0140 ┆ … ┆ 16-00627  ┆ 16-01191  ┆ 16-00731  ┆ 14-00528 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Acetylomi ┆ A2M-K1176 ┆ null      ┆ -0.510944 ┆ … ┆ -0.001547 ┆ null      ┆ -0.715752 ┆ null     │
│ cs        ┆ k         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ A2M-K912k ┆ null      ┆ -1.447282 ┆ … ┆ -0.494212 ┆ null      ┆ 0.459282  ┆ null     │
│ cs        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ ABCE1-K34 ┆ -0.119836 ┆ null      ┆ … ┆ null      ┆ -0.769978 ┆ null      ┆ -0.47538 │
│ cs        ┆ 3k        ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Acetylomi ┆ ABCE1-K43 ┆ -0.292101 ┆ -0.383407 ┆ … ┆ 0.712604  ┆ 0.151771  ┆ 0.865964  ┆ -0.03618 │
│ cs        ┆ 1k        ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ Acetylomi ┆ ABHD10-K6 ┆ -0.880812 ┆ 0.040963  ┆ … ┆ null      ┆ -1.501626 ┆ null      ┆ 1.311712 │
│ cs        ┆ 9k        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Acetylomi ┆ ZW10-K634 ┆ 0.464873  ┆ 0.206216  ┆ … ┆ 0.787118  ┆ -0.381535 ┆ -0.416321 ┆ -0.51496 │
│ cs        ┆ k         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ Acetylomi ┆ ZYX-K25k  ┆ -0.724276 ┆ 0.174708  ┆ … ┆ 0.317452  ┆ 0.283501  ┆ -1.185315 ┆ 0.682768 │
│ cs        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ ZYX-K272k ┆ -1.474535 ┆ -0.860161 ┆ … ┆ -0.861179 ┆ -0.448428 ┆ -1.147123 ┆ null     │
│ cs        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ ZYX-K279k ┆ -0.798836 ┆ 0.32877   ┆ … ┆ -2.049883 ┆ -2.517846 ┆ -1.821148 ┆ 0.890456 │
│ cs        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ ZZZ3-K701 ┆ -0.811519 ┆ -1.704436 ┆ … ┆ null      ┆ null      ┆ -1.665116 ┆ null     │
│ cs        ┆ k         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Lipidomics

In [8]:
_ptrc, _pilot = import_lipids(SYN)
lipid = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Lipidomics").alias("Block"),
        pl.exclude("Block")
    )
)
lipid

[syn71896667:normalized_combat_edata_lipid.csv]: Found existing file at /Users/dylan.ross/.synapseCache/248/166162248/normalized_combat_edata_lipid.csv, skipping download.

shape: (343, 187)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 12-00032  ┆ 11-00503  ┆ … ┆ C-13-0276 ┆ 16-00627  ┆ 16-01191  ┆ 16-00731 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Lipidomic ┆ neg_LPI   ┆ 18.435897 ┆ 19.425027 ┆ … ┆ 18.072983 ┆ 17.876114 ┆ 19.132101 ┆ 18.81077 │
│ s         ┆ 20:4_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPG   ┆ 15.939925 ┆ 13.332694 ┆ … ┆ 16.920046 ┆ 15.077261 ┆ 15.648837 ┆ 17.15972 │
│ s         ┆ 22:6_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPI   ┆ 17.03302  ┆ 16.27659  ┆ … ┆ 16.242012 ┆ 15.510758 ┆ 17.170929 ┆ 16.81890 │
│ s         ┆ 20:3_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPG   ┆ 17.18434  ┆ 13.769529 ┆ … ┆ 15.509279 ┆ 16.09736  ┆ 14.900227 ┆ 16.05541 │
│ s         ┆ 22:5_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPI   ┆ 17.404633 ┆ 16.715682 ┆ … ┆ 17.131718 ┆ 17.139366 ┆ 19.48785  ┆ 17.86525 │
│ s         ┆ 18:1_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Lipidomic ┆ pos_Cer   ┆ 16.706856 ┆ 17.434989 ┆ … ┆ 17.616017 ┆ 17.37841  ┆ 17.140953 ┆ 16.81189 │
│ s         ┆ 43:2;O2|C ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ er 19:1;O ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2/24…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_Cer   ┆ 21.430936 ┆ 18.744501 ┆ … ┆ 19.872285 ┆ 20.452206 ┆ 21.536347 ┆ 21.25364 │
│ s         ┆ 44:2;O2|C ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│           ┆ er 18:1;O ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2/26…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_HexCe ┆ 19.047234 ┆ 18.123438 ┆ … ┆ 20.115742 ┆ 18.283173 ┆ 18.326228 ┆ 18.51909 │
│ s         ┆ r 40:2;O2 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ |HexCer   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:1…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_HexCe ┆ 24.510537 ┆ 21.222264 ┆ … ┆ 24.459727 ┆ 24.15236  ┆ 22.215316 ┆ 22.97539 │
│ s         ┆ r 42:1;O2 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ |HexCer   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:1…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_HexCe ┆ 24.443836 ┆ 22.097968 ┆ … ┆ 25.112109 ┆ 24.738319 ┆ 23.472955 ┆ 24.16746 │
│ s         ┆ r 42:2;O2 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ |HexCer   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:1…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Metabolomics

In [9]:
_ptrc, _pilot = import_metabolites(SYN)
metab = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Metabolomics").alias("Block"),
        pl.exclude("Block")
    )
)
metab

[syn71896311:rp_normalized_combat_edata_metab.csv]: Found existing file at /Users/dylan.ross/.synapseCache/125/166162125/rp_normalized_combat_edata_metab.csv, skipping download.
[syn25796769:PNNL_clinical_summary_03_03_2021.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/799/76897799/PNNL_clinical_summary_03_03_2021.xlsx, skipping download.
[syn68835814:PTRC_Exp26 Sample Key.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/432/161070432/PTRC_Exp26 Sample Key.xlsx, skipping download.

shape: (49, 187)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 12-00032  ┆ 11-00503  ┆ … ┆ 16-00120  ┆ 16-00292  ┆ 16-01109  ┆ C-98-066 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 5        │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Metabolom ┆ rppos_3.H ┆ 18.560512 ┆ 20.456926 ┆ … ┆ 19.095295 ┆ 18.580408 ┆ 14.865952 ┆ 22.36650 │
│ ics       ┆ ydroxyhex ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ adecanoyl ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ car…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rppos_5.O ┆ 23.962277 ┆ 23.503443 ┆ … ┆ 24.907967 ┆ 26.335303 ┆ 23.470423 ┆ 21.72076 │
│ ics       ┆ xoproline ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Metabolom ┆ rppos_Ace ┆ 25.39362  ┆ 24.277188 ┆ … ┆ 27.611863 ┆ 29.263052 ┆ 23.696274 ┆ 23.24535 │
│ ics       ┆ tyl.L.car ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ nitine    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rppos_Ade ┆ 21.508335 ┆ 22.36418  ┆ … ┆ 25.151434 ┆ 24.224989 ┆ 23.229772 ┆ 20.40903 │
│ ics       ┆ nosine    ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Metabolom ┆ rppos_Arg ┆ 24.116801 ┆ 22.968834 ┆ … ┆ 24.340051 ┆ 24.882837 ┆ 23.879777 ┆ 24.02520 │
│ ics       ┆ inine     ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Metabolom ┆ rpneg_Tau ┆ 24.376623 ┆ 20.904345 ┆ … ┆ 23.952718 ┆ 25.673203 ┆ 21.737884 ┆ 22.43768 │
│ ics       ┆ rine      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ Metabolom ┆ rpneg_Chl ┆ 21.706477 ┆ 19.490344 ┆ … ┆ 21.425277 ┆ 20.920886 ┆ 21.301589 ┆ 18.12989 │
│ ics       ┆ oric.acid ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rpneg_Dod ┆ 24.196554 ┆ 22.685516 ┆ … ┆ 23.727053 ┆ 23.252266 ┆ 25.017811 ┆ 22.30151 │
│ ics       ┆ ecyl.sulf ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ ate       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rpneg_Tri ┆ 26.117349 ┆ 24.377045 ┆ … ┆ 24.482149 ┆ 24.210419 ┆ 25.260618 ┆ 22.75509 │
│ ics       ┆ fluoroace ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆ tic.acid  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rpneg_Uri ┆ 17.583055 ┆ 15.251669 ┆ … ┆ 19.11595  ┆ 20.59161  ┆ 18.299964 ┆ 18.03404 │
│ ics       ┆ c.acid    ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Proteomics

In [10]:
_ptrc, _pilot = import_global(SYN)
prot = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Proteomics").alias("Block"),
        pl.exclude("Block")
    )
)
prot

shape: (8_059, 291)
┌────────────┬─────────┬───────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Block      ┆ Feature ┆ 11-00261  ┆ 11-00503 ┆ … ┆ 16-01191-B ┆ 17-00025- ┆ 17-00741- ┆ 17-00881- │
│ ---        ┆ ---     ┆ ---       ┆ ---      ┆   ┆ ridge      ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str     ┆ f64       ┆ f64      ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆          ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Proteomics ┆ A1BG    ┆ 1.010275  ┆ 1.193825 ┆ … ┆ 0.771347   ┆ -0.732169 ┆ -0.548223 ┆ -0.349491 │
│ Proteomics ┆ A2M     ┆ 0.609935  ┆ 0.59216  ┆ … ┆ -0.170057  ┆ -0.63816  ┆ 0.63802   ┆ 0.221334  │
│ Proteomics ┆ AAAS    ┆ -0.607491 ┆ -0.31949 ┆ … ┆ -2.74196   ┆ -1.093548 ┆ -0.858019 ┆ -1.690165 │
│ Proteomics ┆ AACS    ┆ -0.176501 ┆ 0.313655 ┆ … ┆ -0.343664  ┆ 0.061794  ┆ -0.270661 ┆ -0.613057 │
│ Proteomics ┆ AAGAB   ┆ -0.580698 ┆ -0.4766  ┆ … ┆ -1.963402  ┆ -0.419291 ┆ -0.766389 ┆ -0.549602 │
│ …          ┆ …       ┆ …         ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Proteomics ┆ ZXDC    ┆ 0.190547  ┆ 0.376818 ┆ … ┆ -1.866377  ┆ -0.099113 ┆ -0.373654 ┆ -2.060802 │
│ Proteomics ┆ ZYG11B  ┆ -0.721528 ┆ 0.072547 ┆ … ┆ -0.920332  ┆ -0.011652 ┆ -0.62512  ┆ -1.297572 │
│ Proteomics ┆ ZYX     ┆ 0.810729  ┆ 0.500416 ┆ … ┆ 0.936261   ┆ 1.144919  ┆ 0.285152  ┆ 0.09255   │
│ Proteomics ┆ ZZEF1   ┆ 0.554385  ┆ 0.499288 ┆ … ┆ -0.448383  ┆ 0.703228  ┆ 0.045035  ┆ -0.369072 │
│ Proteomics ┆ ZZZ3    ┆ 0.64401   ┆ 0.187632 ┆ … ┆ -2.725037  ┆ -0.412848 ┆ -0.865195 ┆ -1.737515 │
└────────────┴─────────┴───────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

### Phosphoproteomics

In [11]:
_ptrc, _pilot = import_phospho(SYN)
phospho = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Phosphoproteomics").alias("Block"),
        pl.exclude("Block")
    )
)
phospho

shape: (8_362, 291)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 11-00261  ┆ 11-00503  ┆ … ┆ 16-01191- ┆ 17-00025- ┆ 17-00741- ┆ 17-00881 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ -Bridge  │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Phosphopr ┆ AAAS-S495 ┆ -0.228    ┆ -2.62     ┆ … ┆ -3.043648 ┆ 0.196599  ┆ -0.252866 ┆ -2.05419 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ AAK1-S20s ┆ 0.693856  ┆ 0.408721  ┆ … ┆ null      ┆ 0.559486  ┆ -0.197032 ┆ -0.67747 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ Phosphopr ┆ AAK1-S637 ┆ 0.043272  ┆ 2.317306  ┆ … ┆ -3.538961 ┆ -0.148168 ┆ -2.16566  ┆ -2.46897 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ AAK1-S670 ┆ null      ┆ 0.095059  ┆ … ┆ -1.971776 ┆ 0.181735  ┆ -1.709711 ┆ -1.76173 │
│ oteomics  ┆ sT674tS67 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│           ┆ 8s        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ AAK1-S678 ┆ 2.024118  ┆ 1.650225  ┆ … ┆ 0.822801  ┆ 2.332908  ┆ 0.56749   ┆ -0.07414 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Phosphopr ┆ ZYX-S308s ┆ -0.762722 ┆ -0.153285 ┆ … ┆ -0.23192  ┆ null      ┆ -0.524132 ┆ -1.98997 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ Phosphopr ┆ ZYX-S344s ┆ -0.094336 ┆ -0.973364 ┆ … ┆ 2.091973  ┆ 1.524247  ┆ -1.063089 ┆ -0.03902 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ Phosphopr ┆ ZZEF1-S15 ┆ 1.096836  ┆ 0.326957  ┆ … ┆ -0.722226 ┆ 1.300605  ┆ null      ┆ -0.59494 │
│ oteomics  ┆ 18s       ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ ZZEF1-S25 ┆ 0.980115  ┆ 0.633477  ┆ … ┆ null      ┆ 2.097615  ┆ null      ┆ 0.572866 │
│ oteomics  ┆ 26s       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ ZZZ3-S113 ┆ 0.381575  ┆ -0.437789 ┆ … ┆ -1.352199 ┆ -1.47352  ┆ -0.192961 ┆ -0.78567 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Transcriptomics

In [12]:
def rename_redundant_columns(df):
    cols = []
    count = defaultdict(int)
    for column in df.columns:
        if df.columns.tolist().count(column) > 1:
            cols.append(f"{column}__{count[column] + 1}")
            count[column] += 1
        else:
            cols.append(column)
    df.columns = cols
    return df

In [13]:
_ptrc, _pilot = import_rna(SYN)
rna = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    # rename duplicated columns with suffixes __1, __2, etc.
                    rename_redundant_columns(_ptrc.loc[:, pd.notnull(_ptrc.columns)]), 
                    include_index=True
                ),
                pl.from_pandas(
                    # rename duplicated columns with suffixes __1, __2, etc.
                    rename_redundant_columns(_pilot.loc[:, pd.notnull(_pilot.columns)]),
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Transcriptomics").alias("Block"),
        pl.exclude("Block")
    )
)
rna

[syn64126462:beataml_waves1to4_counts_dbgap.txt]: Found existing file at /Users/dylan.ross/.synapseCache/867/150013867/beataml_waves1to4_counts_dbgap.txt, skipping download.
[syn68820229:RNAseq expression data.txt]: Found existing file at /Users/dylan.ross/.synapseCache/317/160991317/RNAseq expression data.txt, skipping download.
[syn68820228:PilotYR_1_2_metadata_083024_withRNA DN.csv]: Found existing file at /Users/dylan.ross/.synapseCache/316/160991316/PilotYR_1_2_metadata_083024_withRNA DN.csv, skipping download.
[syn64126463:beataml_waves1to4_sample_mapping.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/872/150013872/beataml_waves1to4_sample_mapping.xlsx, skipping download.

shape: (14_372, 734)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 12-00023  ┆ 12-00051  ┆ … ┆ C-05-0927 ┆ C-05-0664 ┆ C-00-1828 ┆ C-98-003 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Transcrip ┆ TSPAN6    ┆ 0.103669  ┆ 0.65572   ┆ … ┆ 0.971454  ┆ 0.0       ┆ 0.622786  ┆ 0.0      │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ DPM1      ┆ 42.2949   ┆ 39.501528 ┆ … ┆ 25.859969 ┆ 59.031227 ┆ 51.696317 ┆ 64.13759 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ Transcrip ┆ SCYL3     ┆ 4.637513  ┆ 4.24828   ┆ … ┆ 4.323122  ┆ 0.0       ┆ 3.348115  ┆ 2.358715 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ FIRRM     ┆ 2.649945  ┆ 0.925847  ┆ … ┆ 6.181564  ┆ 0.0       ┆ 7.112927  ┆ 2.424203 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ FGR       ┆ 432.52939 ┆ 6.684816  ┆ … ┆ 44.141788 ┆ 185.92268 ┆ 11.123702 ┆ 310.2314 │
│ tomics    ┆           ┆ 4         ┆           ┆   ┆           ┆ 7         ┆           ┆ 53       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Transcrip ┆ CEP43__2  ┆ 0.099421  ┆ 0.060466  ┆ … ┆ 0.186329  ┆ 0.0       ┆ 0.597266  ┆ 0.449295 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ C2orf15   ┆ 0.586884  ┆ 0.262833  ┆ … ┆ 0.0       ┆ 0.0       ┆ 1.442321  ┆ 0.154999 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ GRIN2B    ┆ 0.31225   ┆ 1.709153  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ SNURF     ┆ 0.122607  ┆ 0.0       ┆ … ┆ 0.689348  ┆ 0.0       ┆ 0.368276  ┆ 0.23746  │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ C1QTNF3-A ┆ 0.050704  ┆ 0.083261  ┆ … ┆ 0.587979  ┆ 0.0       ┆ 0.228452  ┆ 0.0      │
│ tomics    ┆ MACR      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Combine the (-Omics Data) Tables
(metadata table stays separate with samples as rows, to enable easier subsetting of samples based on metadata)

In [14]:
combined = (
    pl.concat(
        [
            acetyl,
            lipid,
            metab,
            prot,
            phospho,
            rna
        ],
        how="diagonal",
    )
    # keep only the sample columns that are included in the filtered metadata table
    .select(
        ["Block", "Feature"] + meta["Sample"].to_list()
    )
)
combined

shape: (34_470, 286)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Block      ┆ Feature   ┆ 11-00261 ┆ 11-00503 ┆ … ┆ 16-01191- ┆ 17-00025- ┆ 17-00741- ┆ 17-00881- │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str       ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Acetylomic ┆ A2M-K1176 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ k         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ A2M-K912k ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ABCE1-K34 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ 3k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ABCE1-K43 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ 1k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ABHD10-K6 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ 9k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Transcript ┆ CEP43__2  ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ C2orf15   ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ GRIN2B    ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ SNURF     ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ C1QTNF3-A ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ MACR      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Cache the Assembled Tables

In [15]:
meta.write_ipc(META_CACHE)

In [16]:
combined.write_ipc(COMBINED_CACHE)