## Setup

### Imports

In [2]:
import sys
import os 

# necessary to make data loading functions available
# Jupyter server should be running from src/python
sys.path.append(
    os.getcwd()
)

In [3]:
from pilot.data_import import (
    import_acetyl,
    import_global,
    import_lipids,
    import_meta,
    import_metabolites,
    import_phospho,
    import_rna,
    syn_login
)

In [1]:
from collections import defaultdict

import polars as pl
import pandas as pd
import synapseclient as sc
from synapseclient.models import File as scFile

### Synapse login token/session

In [4]:
SYN = syn_login()

UPGRADE AVAILABLE

A more recent version of the Synapse Client (4.12.0) is available. Your version (4.11.0) can be upgraded by typing:
   pip install --upgrade synapseclient

Python Synapse Client version 4.12.0 release notes

https://python-docs.synapse.org/news/


Welcome, dylan.ross!

### Constants

In [16]:
# Jupyter server should be running from src/python
CACHE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.getcwd())),
    "analysis",
    "mutations",
    "_cache"
)

# metadata and combined -omics data saved to Apache arrow files
# for quick and easy loading
META_CACHE = os.path.join(CACHE_DIR, "metadata.arrow")
META_CACHE_CSV = os.path.join(CACHE_DIR, "metadata.csv")
COMBINED_CACHE = os.path.join(CACHE_DIR, "combined_omics_data.arrow")
COMBINED_CACHE_CSV = os.path.join(CACHE_DIR, "combined_omics_data.csv")

# folder ID for storing combined data table on synapse
# (syn74722605/Analysis/Exp26 Analysis/mutations/)
SYN_UPLOAD_FOLDER_ID = "syn74775762"

### Ensure cache directory is available

In [17]:
os.makedirs(CACHE_DIR, exist_ok=True)

## Load Metadata and Each -Omics Dataset separately
### Metadata

In [7]:
meta = (
    pl.from_pandas(
        import_meta(SYN), 
        include_index=True
    )
    .rename({"None": "Sample"})
    # keep only a subset of the mutation data:
    # important mutations from Eisfeld paper
    # https://doi.org/10.1038/s41588-024-01929-x
    .select(
        "Sample",
        "Age",
        "Sex",
        "Race",
        "Study", 
        # for all of the mutation data: 
        #   (implicit) treat "Not measured" as "WT"
        #   (explicit) fill any null values with "WT"
        # convert the column into boolean indicating mutation state
        (pl.col("FLT3_ITD").fill_null("WT") == "Mutant"),
        (pl.col("NPM1").fill_null("WT") == "Mutant"),
    )
    # retain only samples with "White" or "Black" race label
    .filter(pl.col("Race").is_in(["White", "Black"]))
)
meta

[syn69692583:updated_meta.csv]: Found existing file at /Users/dylan.ross/.synapseCache/79/170282079/updated_meta.csv, skipping download.
[syn64126463:beataml_waves1to4_sample_mapping.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/872/150013872/beataml_waves1to4_sample_mapping.xlsx, skipping download.
[syn64126458:1-s2.0-S1535610822003129-mmc2.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/845/150013845/1-s2.0-S1535610822003129-mmc2.xlsx, skipping download.
[syn26427388:beataml_wes_wv1to4_mutations_v4.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/369/83911369/beataml_wes_wv1to4_mutations_v4.xlsx, skipping download.
[syn32533104:beataml_wes_wv1to4_mutations_177_samples.txt]: Found existing file at /Users/dylan.ross/.synapseCache/976/98264976/beataml_wes_wv1to4_mutations_177_samples.txt, skipping download.

shape: (284, 7)
┌─────────────────┬──────┬────────┬───────┬────────────┬──────────┬───────┐
│ Sample          ┆ Age  ┆ Sex    ┆ Race  ┆ Study      ┆ FLT3_ITD ┆ NPM1  │
│ ---             ┆ ---  ┆ ---    ┆ ---   ┆ ---        ┆ ---      ┆ ---   │
│ str             ┆ f64  ┆ str    ┆ str   ┆ str        ┆ bool     ┆ bool  │
╞═════════════════╪══════╪════════╪═══════╪════════════╪══════════╪═══════╡
│ 11-00261        ┆ 74.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ false │
│ 11-00503        ┆ 54.0 ┆ Female ┆ White ┆ BeatAML    ┆ true     ┆ true  │
│ 11-00475        ┆ 65.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ true  │
│ 12-00032        ┆ 70.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ false │
│ 11-00376        ┆ 49.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ true  │
│ …               ┆ …    ┆ …      ┆ …     ┆ …          ┆ …        ┆ …     │
│ 16-01109-Bridge ┆ 33.0 ┆ Male   ┆ Black ┆ pilotStudy ┆ false    ┆ false │
│ 16-01191-Bridge ┆ 65.0 ┆ Female ┆ White ┆ pilotStudy ┆ false    ┆ false │
│ 17-00025-Bridge ┆ 39.0 ┆ Female ┆ White ┆ pilotStudy ┆ true     ┆ true  │
│ 17-00741-Bridge ┆ 20.0 ┆ Male   ┆ White ┆ pilotStudy ┆ false    ┆ false │
│ 17-00881-Bridge ┆ 76.0 ┆ Female ┆ White ┆ pilotStudy ┆ false    ┆ false │
└─────────────────┴──────┴────────┴───────┴────────────┴──────────┴───────┘

### Acetylomics

In [8]:
_ptrc, _pilot = import_acetyl(SYN)
acetyl = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Acetylomics").alias("Block"),
        pl.exclude("Block")
    )
)
acetyl

[syn53484994:ptrc_ex10_crosstab_acetyl_siteID_corrected_relaxed.txt]: Found existing file at /Users/dylan.ross/.synapseCache/792/133616792/ptrc_ex10_crosstab_acetyl_siteID_corrected_relaxed.txt, skipping download.
[syn69075568:ptrc_ex26_crosstab_acetyl_siteid_corrected.txt]: Found existing file at /Users/dylan.ross/.synapseCache/514/161922514/ptrc_ex26_crosstab_acetyl_siteid_corrected.txt, skipping download.
[syn25807733:Ex10_metadata.txt]: Found existing file at /Users/dylan.ross/.synapseCache/668/78060668/Ex10_metadata.txt, skipping download.
[syn68835814:PTRC_Exp26 Sample Key.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/432/161070432/PTRC_Exp26 Sample Key.xlsx, skipping download.

shape: (935, 310)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Block      ┆ Feature   ┆ 12-00032 ┆ 11-00503 ┆ … ┆ 16-00627- ┆ 16-01191- ┆ 16-00731- ┆ 14-00528- │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str       ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Acetylomic ┆ ACAA2-K23 ┆ -0.762   ┆ -1.32    ┆ … ┆ -1.067707 ┆ 0.360673  ┆ -0.778423 ┆ -1.686547 │
│ s          ┆ 4k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACAD9-K20 ┆ null     ┆ -0.357   ┆ … ┆ 0.207464  ┆ -0.602037 ┆ -0.395339 ┆ null      │
│ s          ┆ 2k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADM-K30 ┆ null     ┆ -0.0232  ┆ … ┆ -0.672011 ┆ -0.994443 ┆ -1.563158 ┆ null      │
│ s          ┆ 4k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADVL-K2 ┆ null     ┆ 0.81     ┆ … ┆ -2.109005 ┆ -1.049815 ┆ -1.389221 ┆ 0.002312  │
│ s          ┆ 78k       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADVL-K2 ┆ -2.19    ┆ 0.421    ┆ … ┆ -0.655982 ┆ -0.471836 ┆ -0.293991 ┆ 0.303983  │
│ s          ┆ 98k       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Acetylomic ┆ ZNF292-K2 ┆ null     ┆ 0.732    ┆ … ┆ -1.244314 ┆ -0.255493 ┆ -0.561383 ┆ 0.394092  │
│ s          ┆ 042k      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ZNF638-K1 ┆ 1.3      ┆ 0.884    ┆ … ┆ 0.055864  ┆ -0.864431 ┆ -0.666152 ┆ 1.740746  │
│ s          ┆ 477k      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ZNF638-K8 ┆ null     ┆ 0.275    ┆ … ┆ -0.332663 ┆ 1.147618  ┆ 0.976461  ┆ 1.454743  │
│ s          ┆ 6k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ZW10-K634 ┆ 0.295    ┆ null     ┆ … ┆ 0.787118  ┆ -0.381535 ┆ -0.416321 ┆ -0.514967 │
│ s          ┆ k         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ZYX-K25k  ┆ 0.0123   ┆ -1.02    ┆ … ┆ 0.317452  ┆ 0.283501  ┆ -1.185315 ┆ 0.682768  │
│ s          ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Lipidomics

In [9]:
_ptrc, _pilot = import_lipids(SYN)
lipid = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Lipidomics").alias("Block"),
        pl.exclude("Block")
    )
)
lipid

[syn71896673:f_data_lipid.csv]: Found existing file at /Users/dylan.ross/.synapseCache/689/170119689/f_data_lipid.csv, skipping download.
[syn71896667:normalized_combat_edata_lipid.csv]: Found existing file at /Users/dylan.ross/.synapseCache/248/166162248/normalized_combat_edata_lipid.csv, skipping download.

shape: (343, 187)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 12-00032  ┆ 11-00503  ┆ … ┆ C-13-0276 ┆ 16-00627  ┆ 16-01191  ┆ 16-00731 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Lipidomic ┆ neg_LPI   ┆ 18.435897 ┆ 19.425027 ┆ … ┆ 18.072983 ┆ 17.876114 ┆ 19.132101 ┆ 18.81077 │
│ s         ┆ 20:4_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPG   ┆ 15.939925 ┆ 13.332694 ┆ … ┆ 16.920046 ┆ 15.077261 ┆ 15.648837 ┆ 17.15972 │
│ s         ┆ 22:6_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPI   ┆ 17.03302  ┆ 16.27659  ┆ … ┆ 16.242012 ┆ 15.510758 ┆ 17.170929 ┆ 16.81890 │
│ s         ┆ 20:3_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPG   ┆ 17.18434  ┆ 13.769529 ┆ … ┆ 15.509279 ┆ 16.09736  ┆ 14.900227 ┆ 16.05541 │
│ s         ┆ 22:5_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPI   ┆ 17.404633 ┆ 16.715682 ┆ … ┆ 17.131718 ┆ 17.139366 ┆ 19.48785  ┆ 17.86525 │
│ s         ┆ 18:1_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Lipidomic ┆ pos_Cer   ┆ 16.706856 ┆ 17.434989 ┆ … ┆ 17.616017 ┆ 17.37841  ┆ 17.140953 ┆ 16.81189 │
│ s         ┆ 43:2;O2|C ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ er 19:1;O ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2/24…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_Cer   ┆ 21.430936 ┆ 18.744501 ┆ … ┆ 19.872285 ┆ 20.452206 ┆ 21.536347 ┆ 21.25364 │
│ s         ┆ 44:2;O2|C ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│           ┆ er 18:1;O ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2/26…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_HexCe ┆ 19.047234 ┆ 18.123438 ┆ … ┆ 20.115742 ┆ 18.283173 ┆ 18.326228 ┆ 18.51909 │
│ s         ┆ r 40:2;O2 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ |HexCer   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:1…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_HexCe ┆ 24.510537 ┆ 21.222264 ┆ … ┆ 24.459727 ┆ 24.15236  ┆ 22.215316 ┆ 22.97539 │
│ s         ┆ r 42:1;O2 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ |HexCer   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:1…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ pos_HexCe ┆ 24.443836 ┆ 22.097968 ┆ … ┆ 25.112109 ┆ 24.738319 ┆ 23.472955 ┆ 24.16746 │
│ s         ┆ r 42:2;O2 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ |HexCer   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:1…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Metabolomics

In [10]:
_ptrc, _pilot = import_metabolites(SYN)
metab = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Metabolomics").alias("Block"),
        pl.exclude("Block")
    )
)
metab

[syn71896311:rp_normalized_combat_edata_metab.csv]: Found existing file at /Users/dylan.ross/.synapseCache/125/166162125/rp_normalized_combat_edata_metab.csv, skipping download.
[syn25796769:PNNL_clinical_summary_03_03_2021.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/799/76897799/PNNL_clinical_summary_03_03_2021.xlsx, skipping download.
[syn68835814:PTRC_Exp26 Sample Key.xlsx]: Found existing file at /Users/dylan.ross/.synapseCache/432/161070432/PTRC_Exp26 Sample Key.xlsx, skipping download.

shape: (49, 187)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 12-00032  ┆ 11-00503  ┆ … ┆ 16-00120  ┆ 16-00292  ┆ 16-01109  ┆ C-98-066 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 5        │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Metabolom ┆ rppos_3.H ┆ 18.560512 ┆ 20.456926 ┆ … ┆ 19.095295 ┆ 18.580408 ┆ 14.865952 ┆ 22.36650 │
│ ics       ┆ ydroxyhex ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ adecanoyl ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ car…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rppos_5.O ┆ 23.962277 ┆ 23.503443 ┆ … ┆ 24.907967 ┆ 26.335303 ┆ 23.470423 ┆ 21.72076 │
│ ics       ┆ xoproline ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Metabolom ┆ rppos_Ace ┆ 25.39362  ┆ 24.277188 ┆ … ┆ 27.611863 ┆ 29.263052 ┆ 23.696274 ┆ 23.24535 │
│ ics       ┆ tyl.L.car ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ nitine    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rppos_Ade ┆ 21.508335 ┆ 22.36418  ┆ … ┆ 25.151434 ┆ 24.224989 ┆ 23.229772 ┆ 20.40903 │
│ ics       ┆ nosine    ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Metabolom ┆ rppos_Arg ┆ 24.116801 ┆ 22.968834 ┆ … ┆ 24.340051 ┆ 24.882837 ┆ 23.879777 ┆ 24.02520 │
│ ics       ┆ inine     ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Metabolom ┆ rpneg_Tau ┆ 24.376623 ┆ 20.904345 ┆ … ┆ 23.952718 ┆ 25.673203 ┆ 21.737884 ┆ 22.43768 │
│ ics       ┆ rine      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ Metabolom ┆ rpneg_Chl ┆ 21.706477 ┆ 19.490344 ┆ … ┆ 21.425277 ┆ 20.920886 ┆ 21.301589 ┆ 18.12989 │
│ ics       ┆ oric.acid ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rpneg_Dod ┆ 24.196554 ┆ 22.685516 ┆ … ┆ 23.727053 ┆ 23.252266 ┆ 25.017811 ┆ 22.30151 │
│ ics       ┆ ecyl.sulf ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ ate       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rpneg_Tri ┆ 26.117349 ┆ 24.377045 ┆ … ┆ 24.482149 ┆ 24.210419 ┆ 25.260618 ┆ 22.75509 │
│ ics       ┆ fluoroace ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆ tic.acid  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Metabolom ┆ rpneg_Uri ┆ 17.583055 ┆ 15.251669 ┆ … ┆ 19.11595  ┆ 20.59161  ┆ 18.299964 ┆ 18.03404 │
│ ics       ┆ c.acid    ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Proteomics

In [11]:
_ptrc, _pilot = import_global(SYN)
prot = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Proteomics").alias("Block"),
        pl.exclude("Block")
    )
)
prot

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

[syn73755181:global_beataml_batch_corrected.csv]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/260422_prep_PR/amlMultidrugResistance/aml_outcome_disparities/src/python/data/global_beataml_batch_corrected.csv, skipping download.

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

[syn73755182:global_pilot_batch_corrected.csv]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/260422_prep_PR/amlMultidrugResistance/aml_outcome_disparities/src/python/data/global_pilot_batch_corrected.csv, skipping download.

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

shape: (8_059, 291)
┌────────────┬─────────┬───────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Block      ┆ Feature ┆ 11-00261  ┆ 11-00503 ┆ … ┆ 16-01191-B ┆ 17-00025- ┆ 17-00741- ┆ 17-00881- │
│ ---        ┆ ---     ┆ ---       ┆ ---      ┆   ┆ ridge      ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str     ┆ f64       ┆ f64      ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆          ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Proteomics ┆ A1BG    ┆ 1.010275  ┆ 1.193825 ┆ … ┆ 0.771347   ┆ -0.732169 ┆ -0.548223 ┆ -0.349491 │
│ Proteomics ┆ A2M     ┆ 0.609935  ┆ 0.59216  ┆ … ┆ -0.170057  ┆ -0.63816  ┆ 0.63802   ┆ 0.221334  │
│ Proteomics ┆ AAAS    ┆ -0.607491 ┆ -0.31949 ┆ … ┆ -2.74196   ┆ -1.093548 ┆ -0.858019 ┆ -1.690165 │
│ Proteomics ┆ AACS    ┆ -0.176501 ┆ 0.313655 ┆ … ┆ -0.343664  ┆ 0.061794  ┆ -0.270661 ┆ -0.613057 │
│ Proteomics ┆ AAGAB   ┆ -0.580698 ┆ -0.4766  ┆ … ┆ -1.963402  ┆ -0.419291 ┆ -0.766389 ┆ -0.549602 │
│ …          ┆ …       ┆ …         ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Proteomics ┆ ZXDC    ┆ 0.190547  ┆ 0.376818 ┆ … ┆ -1.866377  ┆ -0.099113 ┆ -0.373654 ┆ -2.060802 │
│ Proteomics ┆ ZYG11B  ┆ -0.721528 ┆ 0.072547 ┆ … ┆ -0.920332  ┆ -0.011652 ┆ -0.62512  ┆ -1.297572 │
│ Proteomics ┆ ZYX     ┆ 0.810729  ┆ 0.500416 ┆ … ┆ 0.936261   ┆ 1.144919  ┆ 0.285152  ┆ 0.09255   │
│ Proteomics ┆ ZZEF1   ┆ 0.554385  ┆ 0.499288 ┆ … ┆ -0.448383  ┆ 0.703228  ┆ 0.045035  ┆ -0.369072 │
│ Proteomics ┆ ZZZ3    ┆ 0.64401   ┆ 0.187632 ┆ … ┆ -2.725037  ┆ -0.412848 ┆ -0.865195 ┆ -1.737515 │
└────────────┴─────────┴───────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

### Phosphoproteomics

In [12]:
_ptrc, _pilot = import_phospho(SYN)
phospho = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    _ptrc, 
                    include_index=True
                ),
                pl.from_pandas(
                    _pilot, 
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Phosphoproteomics").alias("Block"),
        pl.exclude("Block")
    )
)
phospho

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

[syn73754460:phospho_beataml_batch_corrected.csv]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/260422_prep_PR/amlMultidrugResistance/aml_outcome_disparities/src/python/data/phospho_beataml_batch_corrected.csv, skipping download.

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

[syn73754465:phospho_pilot_batch_corrected.csv]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/260422_prep_PR/amlMultidrugResistance/aml_outcome_disparities/src/python/data/phospho_pilot_batch_corrected.csv, skipping download.

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

shape: (8_362, 291)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 11-00261  ┆ 11-00503  ┆ … ┆ 16-01191- ┆ 17-00025- ┆ 17-00741- ┆ 17-00881 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ -Bridge  │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Phosphopr ┆ AAAS-S495 ┆ -0.228    ┆ -2.62     ┆ … ┆ -3.043648 ┆ 0.196599  ┆ -0.252866 ┆ -2.05419 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ AAK1-S20s ┆ 0.693856  ┆ 0.408721  ┆ … ┆ null      ┆ 0.559486  ┆ -0.197032 ┆ -0.67747 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ Phosphopr ┆ AAK1-S637 ┆ 0.043272  ┆ 2.317306  ┆ … ┆ -3.538961 ┆ -0.148168 ┆ -2.16566  ┆ -2.46897 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ AAK1-S670 ┆ null      ┆ 0.095059  ┆ … ┆ -1.971776 ┆ 0.181735  ┆ -1.709711 ┆ -1.76173 │
│ oteomics  ┆ sT674tS67 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│           ┆ 8s        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ AAK1-S678 ┆ 2.024118  ┆ 1.650225  ┆ … ┆ 0.822801  ┆ 2.332908  ┆ 0.56749   ┆ -0.07414 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Phosphopr ┆ ZYX-S308s ┆ -0.762722 ┆ -0.153285 ┆ … ┆ -0.23192  ┆ null      ┆ -0.524132 ┆ -1.98997 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ Phosphopr ┆ ZYX-S344s ┆ -0.094336 ┆ -0.973364 ┆ … ┆ 2.091973  ┆ 1.524247  ┆ -1.063089 ┆ -0.03902 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ Phosphopr ┆ ZZEF1-S15 ┆ 1.096836  ┆ 0.326957  ┆ … ┆ -0.722226 ┆ 1.300605  ┆ null      ┆ -0.59494 │
│ oteomics  ┆ 18s       ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ ZZEF1-S25 ┆ 0.980115  ┆ 0.633477  ┆ … ┆ null      ┆ 2.097615  ┆ null      ┆ 0.572866 │
│ oteomics  ┆ 26s       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ ZZZ3-S113 ┆ 0.381575  ┆ -0.437789 ┆ … ┆ -1.352199 ┆ -1.47352  ┆ -0.192961 ┆ -0.78567 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Transcriptomics

In [13]:
def rename_redundant_columns(df):
    cols = []
    count = defaultdict(int)
    for column in df.columns:
        if df.columns.tolist().count(column) > 1:
            cols.append(f"{column}__{count[column] + 1}")
            count[column] += 1
        else:
            cols.append(column)
    df.columns = cols
    return df

In [14]:
_ptrc, _pilot = import_rna(SYN)
rna = (
    (_df := 
        pl.concat(
            [
                pl.from_pandas(
                    # rename duplicated columns with suffixes __1, __2, etc.
                    rename_redundant_columns(_ptrc.loc[:, pd.notnull(_ptrc.columns)]), 
                    include_index=True
                ),
                pl.from_pandas(
                    # rename duplicated columns with suffixes __1, __2, etc.
                    rename_redundant_columns(_pilot.loc[:, pd.notnull(_pilot.columns)]),
                    include_index=True
                ),
            ],
            how="diagonal"
        )
    )
    .select(pl.exclude("None"))
    .transpose(
        include_header=True, 
        header_name="Feature", 
        column_names=_df["None"].to_list()
    )
    .select(
        pl.lit("Transcriptomics").alias("Block"),
        pl.exclude("Block")
    )
)
rna

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

[syn72665045:RNAseq_beataml_batch_corrected.csv]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/260422_prep_PR/amlMultidrugResistance/aml_outcome_disparities/src/python/data/RNAseq_beataml_batch_corrected.csv, skipping download.

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]
Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

[syn72665034:RNAseq_pilot_batch_corrected.csv]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/260422_prep_PR/amlMultidrugResistance/aml_outcome_disparities/src/python/data/RNAseq_pilot_batch_corrected.csv, skipping download.

Downloading files:   0%|                                                                     | 0.00/1.00 [00:00<?, ?B/s]

shape: (22_116, 734)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 12-00023  ┆ 12-00051  ┆ … ┆ C-05-0927 ┆ C-05-0664 ┆ C-00-1828 ┆ C-98-003 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Transcrip ┆ TSPAN6    ┆ 0.103667  ┆ 0.655698  ┆ … ┆ 0.966417  ┆ 0.0       ┆ 0.616858  ┆ 0.0      │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ DPM1      ┆ 42.29404  ┆ 39.500211 ┆ … ┆ 25.725908 ┆ 58.2125   ┆ 51.204308 ┆ 63.63234 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ Transcrip ┆ SCYL3     ┆ 4.637419  ┆ 4.248138  ┆ … ┆ 4.300711  ┆ 0.0       ┆ 3.31625   ┆ 2.340134 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ FIRRM     ┆ 2.649891  ┆ 0.925816  ┆ … ┆ 6.149518  ┆ 0.0       ┆ 7.045231  ┆ 2.405106 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ FGR       ┆ 432.52060 ┆ 6.684593  ┆ … ┆ 43.912952 ┆ 183.34405 ┆ 11.017835 ┆ 307.7875 │
│ tomics    ┆           ┆ 1         ┆           ┆   ┆           ┆ 2         ┆           ┆ 71       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Transcrip ┆ ENSG00000 ┆ 0.043143  ┆ 0.047229  ┆ … ┆ 0.542961  ┆ 0.0       ┆ 0.385077  ┆ 0.248704 │
│ tomics    ┆ 273451    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ ENSG00000 ┆ 0.720232  ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.2795    ┆ 0.722066 │
│ tomics    ┆ 273456    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ ENSG00000 ┆ 0.611293  ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2.349258 │
│ tomics    ┆ 273464    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ ENSG00000 ┆ 0.354156  ┆ 0.058155  ┆ … ┆ 0.14857   ┆ 0.0       ┆ 0.316105  ┆ 0.408317 │
│ tomics    ┆ 273472    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ ENSG00000 ┆ 0.0       ┆ 0.012735  ┆ … ┆ 0.0488    ┆ 0.0       ┆ 0.103829  ┆ 0.067059 │
│ tomics    ┆ 273489    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Combine the (-Omics Data) Tables
(metadata table stays separate with samples as rows, to enable easier subsetting of samples based on metadata)

In [15]:
combined = (
    pl.concat(
        [
            acetyl,
            lipid,
            metab,
            prot,
            phospho,
            rna
        ],
        how="diagonal",
    )
    # keep only the sample columns that are included in the filtered metadata table
    .select(
        ["Block", "Feature"] + meta["Sample"].to_list()
    )
)
combined

shape: (39_864, 286)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Block      ┆ Feature   ┆ 11-00261 ┆ 11-00503 ┆ … ┆ 16-01191- ┆ 17-00025- ┆ 17-00741- ┆ 17-00881- │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str       ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Acetylomic ┆ ACAA2-K23 ┆ -2.79    ┆ -1.32    ┆ … ┆ 0.360673  ┆ 0.027206  ┆ -0.568194 ┆ 0.311076  │
│ s          ┆ 4k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACAD9-K20 ┆ -0.195   ┆ -0.357   ┆ … ┆ -0.602037 ┆ 0.194048  ┆ null      ┆ null      │
│ s          ┆ 2k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADM-K30 ┆ -0.129   ┆ -0.0232  ┆ … ┆ -0.994443 ┆ -0.024539 ┆ -0.595167 ┆ null      │
│ s          ┆ 4k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADVL-K2 ┆ 0.272    ┆ 0.81     ┆ … ┆ -1.049815 ┆ 0.351727  ┆ -0.419173 ┆ -1.870117 │
│ s          ┆ 78k       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADVL-K2 ┆ -0.622   ┆ 0.421    ┆ … ┆ -0.471836 ┆ -0.166835 ┆ -1.296326 ┆ -0.359604 │
│ s          ┆ 98k       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 273451    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 273456    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 273464    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 273472    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 273489    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Cache the Assembled Tables

In [18]:
meta.write_ipc(META_CACHE)

In [19]:
meta.write_csv(META_CACHE_CSV)

In [20]:
combined.write_ipc(COMBINED_CACHE)

In [21]:
combined.write_csv(COMBINED_CACHE_CSV)

## Upload assembled tables to synapse
I think this should only be done once to initialize the entries on synapse. After this, I think future updates should use the synapse IDs to upload updated copies?

In [22]:
syn_meta_ipc = scFile(
    path=META_CACHE,
    parent_id=SYN_UPLOAD_FOLDER_ID
)
syn_meta_ipc.store()
print(syn_meta_ipc.id)

SynapseHTTPError: 403 Client Error: insufficient_scope. Request lacks scope(s) required by this service: modify

Based on the above error, there seems to be a permission issue. I manually uploaded the files I am trying to cache and will come back and fix this code later to automatically update these files on synapse, which should not need to happen very often.

Synapse IDs:
- `metadata.csv`: syn74775940
- `metadata.arrow`: syn74775944
- `combined_omics_data.csv`: syn74775999
- `combined_omics_data.arrow`: syn74775996