## Setup

### Imports

In [1]:
import os

import polars as pl
import pandas as pd

import synapseclient

### Constants

In [2]:
# Jupyter server should be running from src/python
# assumes auth_token.txt exists in src/python as described in setup instructions
AUTH_TOKEN = os.path.abspath("auth_token.txt")

# cached metadata table, parquet format, on synapse 
META_CACHE_SYNID = "syn74775994"

# cached combined -omics data table, parquet format, on synapse
OMICS_CACHE_SYNID = "syn74775996"

# Jupyter server should be running from src/python
LIMMA_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.getcwd())),
    "analysis",
    "mutations",
    "_cache",
    "limma"
)

In [3]:
# ensure limma directory exists
os.makedirs(LIMMA_DIR, exist_ok=True)

### Synapse login

In [4]:
with open(AUTH_TOKEN, "r") as atf:
    SYN = synapseclient.login(authToken=atf.read())

UPGRADE AVAILABLE

A more recent version of the Synapse Client (4.14.0) is available. Your version (4.11.0) can be upgraded by typing:
   pip install --upgrade synapseclient

Python Synapse Client version 4.14.0 release notes

https://python-docs.synapse.org/news/


Welcome, dylan.ross!

### Load metadata and omics data from cache

In [5]:
meta = pl.read_parquet(SYN.get(META_CACHE_SYNID).path)
meta

[WARNING] /var/folders/nb/ykfs58f552d0d0jd_2jnkx_80000gp/T/ipykernel_56464/3955249378.py:1: DeprecationWarning: Call to deprecated method get. (To be removed in 5.0.0. Use `from synapseclient.operations import get` instead.) -- Deprecated since version 4.11.0.
  meta = pl.read_parquet(SYN.get(META_CACHE_SYNID).path)

[syn74775994:metadata.parquet]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/261016_diffex_overview/diffex_overview/aml_outcome_disparities/analysis/mutations/_cache/metadata.parquet, skipping download.

shape: (284, 7)
┌─────────────────┬──────┬────────┬───────┬────────────┬──────────┬───────┐
│ Sample          ┆ Age  ┆ Sex    ┆ Race  ┆ Study      ┆ FLT3_ITD ┆ NPM1  │
│ ---             ┆ ---  ┆ ---    ┆ ---   ┆ ---        ┆ ---      ┆ ---   │
│ str             ┆ f64  ┆ str    ┆ str   ┆ str        ┆ bool     ┆ bool  │
╞═════════════════╪══════╪════════╪═══════╪════════════╪══════════╪═══════╡
│ 11-00261        ┆ 74.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ false │
│ 11-00503        ┆ 54.0 ┆ Female ┆ White ┆ BeatAML    ┆ true     ┆ true  │
│ 11-00475        ┆ 65.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ true  │
│ 12-00032        ┆ 70.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ false │
│ 11-00376        ┆ 49.0 ┆ Male   ┆ White ┆ BeatAML    ┆ true     ┆ true  │
│ …               ┆ …    ┆ …      ┆ …     ┆ …          ┆ …        ┆ …     │
│ 16-01109-Bridge ┆ 33.0 ┆ Male   ┆ Black ┆ pilotStudy ┆ false    ┆ false │
│ 16-01191-Bridge ┆ 65.0 ┆ Female ┆ White ┆ pilotStudy ┆ false    ┆ false │
│ 17-00025-Bridge ┆ 39.0 ┆ Female ┆ White ┆ pilotStudy ┆ true     ┆ true  │
│ 17-00741-Bridge ┆ 20.0 ┆ Male   ┆ White ┆ pilotStudy ┆ false    ┆ false │
│ 17-00881-Bridge ┆ 76.0 ┆ Female ┆ White ┆ pilotStudy ┆ false    ┆ false │
└─────────────────┴──────┴────────┴───────┴────────────┴──────────┴───────┘

In [6]:
combined = pl.read_parquet(SYN.get(OMICS_CACHE_SYNID).path)
combined

[WARNING] /var/folders/nb/ykfs58f552d0d0jd_2jnkx_80000gp/T/ipykernel_56464/4040283258.py:1: DeprecationWarning: Call to deprecated method get. (To be removed in 5.0.0. Use `from synapseclient.operations import get` instead.) -- Deprecated since version 4.11.0.
  combined = pl.read_parquet(SYN.get(OMICS_CACHE_SYNID).path)

[syn74775996:combined_omics_data.parquet]: Found existing file at /Users/dylan.ross/Projects/AML_outcome_disparities/261016_diffex_overview/diffex_overview/aml_outcome_disparities/analysis/mutations/_cache/combined_omics_data.parquet, skipping download.

shape: (34_074, 286)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ OmicsType  ┆ Feature   ┆ 11-00261 ┆ 11-00503 ┆ … ┆ 16-01191- ┆ 17-00025- ┆ 17-00741- ┆ 17-00881- │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str       ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Acetylomic ┆ ACAA2-K23 ┆ -2.79    ┆ -1.32    ┆ … ┆ 0.360673  ┆ 0.027206  ┆ -0.568194 ┆ 0.311076  │
│ s          ┆ 4k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACAD9-K20 ┆ -0.195   ┆ -0.357   ┆ … ┆ -0.602037 ┆ 0.194048  ┆ -0.508715 ┆ -0.138507 │
│ s          ┆ 2k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADM-K30 ┆ -0.129   ┆ -0.0232  ┆ … ┆ -0.994443 ┆ -0.024539 ┆ -0.595167 ┆ -1.370965 │
│ s          ┆ 4k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADVL-K2 ┆ 0.272    ┆ 0.81     ┆ … ┆ -1.049815 ┆ 0.351727  ┆ -0.419173 ┆ -1.870117 │
│ s          ┆ 78k       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ACADVL-K2 ┆ -0.622   ┆ 0.421    ┆ … ┆ -0.471836 ┆ -0.166835 ┆ -1.296326 ┆ -0.359604 │
│ s          ┆ 98k       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 266232    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 201863    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 206926    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 264386    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ ENSG00000 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ 199053    ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# report on the number of features in each block
combined.group_by("OmicsType").len().sort("len", descending=True)

shape: (6, 2)
┌───────────────────┬───────┐
│ OmicsType         ┆ len   │
│ ---               ┆ ---   │
│ str               ┆ u32   │
╞═══════════════════╪═══════╡
│ Transcriptomics   ┆ 17878 │
│ Proteomics        ┆ 7966  │
│ Phosphoproteomics ┆ 7200  │
│ Acetylomics       ┆ 638   │
│ Lipidomics        ┆ 343   │
│ Metabolomics      ┆ 49    │
└───────────────────┴───────┘

## set up for differential expression using `limma`

In [8]:
# ensure alignment of sample order from omics data and metadata
combined_samples = [c for c in combined.columns if c not in ["OmicsType", "Feature"]]
meta_samples = meta["Sample"].to_list()
assert combined_samples == meta_samples

In [9]:
# select out metadata needed to set up for limma
limma_meta = (
    meta
    .with_columns(
        pl.concat_str([
            pl.col("Race"),
            pl.lit("_NPM1"),
            pl.when("NPM1").then(pl.lit("+")).otherwise(pl.lit("-")),
            pl.lit("/FLT3-ITD"),
            pl.when("FLT3_ITD").then(pl.lit("+")).otherwise(pl.lit("-")),
        ])
        .alias("Group")
    )
    .select("Sample", "Group")
    .to_pandas()
    # polars DF → pandas DF
    .set_index("Sample")
)

limma_meta

                                 Group
Sample
11-00261         White_NPM1-/FLT3-ITD+
11-00503         White_NPM1+/FLT3-ITD+
11-00475         White_NPM1+/FLT3-ITD+
12-00032         White_NPM1-/FLT3-ITD+
11-00376         White_NPM1+/FLT3-ITD+
...                                ...
16-01109-Bridge  Black_NPM1-/FLT3-ITD-
16-01191-Bridge  White_NPM1-/FLT3-ITD-
17-00025-Bridge  White_NPM1+/FLT3-ITD+
17-00741-Bridge  White_NPM1-/FLT3-ITD-
17-00881-Bridge  White_NPM1-/FLT3-ITD-

[284 rows x 1 columns]

In [10]:
limma_design = (pd.get_dummies(limma_meta["Group"], dtype=float))

limma_design

,Black_NPM1+/FLT3-ITD+,Black_NPM1+/FLT3-ITD-,Black_NPM1-/FLT3-ITD+,Black_NPM1-/FLT3-ITD-,White_NPM1+/FLT3-ITD+,White_NPM1+/FLT3-ITD-,White_NPM1-/FLT3-ITD+,White_NPM1-/FLT3-ITD-
Sample,,,,,,,,
11-00261,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11-00503,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11-00475,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12-00032,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11-00376,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
16-01109-Bridge,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16-01191-Bridge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17-00025-Bridge,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
17-00741-Bridge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17-00881-Bridge,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
limma_contrast = pd.DataFrame(
    0.,
    index=limma_design.columns.tolist(),
    columns=[
        # population comparison (-/-)
        "Black_NPM1-/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-",
        # NPM1+ vs NPM1-
        "Black_NPM1+/FLT3-ITD-_vs_Black_NPM1-/FLT3-ITD-",
        "White_NPM1+/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-",
        # FLT3-ITD+ vs FLT3-ITD-
        "Black_NPM1-/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD-",
        "White_NPM1-/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD-",
        # (+/+) vs NPM1+
        "Black_NPM1+/FLT3-ITD+_vs_Black_NPM1+/FLT3-ITD-",
        "White_NPM1+/FLT3-ITD+_vs_White_NPM1+/FLT3-ITD-",
        # (+/+) vs FLT3-ITD+
        "Black_NPM1+/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD+",
        "White_NPM1+/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD+",
    ]
)

# define weights for contrasts
# population comparison (-/-)
limma_contrast.loc["Black_NPM1-/FLT3-ITD-", "Black_NPM1-/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-"] = 1.0
limma_contrast.loc["White_NPM1-/FLT3-ITD-", "Black_NPM1-/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-"] = -1.0
# NPM1+ vs NPM1-
limma_contrast.loc["Black_NPM1+/FLT3-ITD-", "Black_NPM1+/FLT3-ITD-_vs_Black_NPM1-/FLT3-ITD-"] = 1.0
limma_contrast.loc["Black_NPM1-/FLT3-ITD-", "Black_NPM1+/FLT3-ITD-_vs_Black_NPM1-/FLT3-ITD-"] = -1.0
limma_contrast.loc["White_NPM1+/FLT3-ITD-", "White_NPM1+/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-"] = 1.0
limma_contrast.loc["White_NPM1-/FLT3-ITD-", "White_NPM1+/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-"] = -1.0
# FLT3-ITD+ vs FLT3-ITD-
limma_contrast.loc["Black_NPM1-/FLT3-ITD+", "Black_NPM1-/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD-"] = 1.0
limma_contrast.loc["Black_NPM1-/FLT3-ITD-", "Black_NPM1-/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD-"] = -1.0
limma_contrast.loc["White_NPM1-/FLT3-ITD+", "White_NPM1-/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD-"] = 1.0
limma_contrast.loc["White_NPM1-/FLT3-ITD-", "White_NPM1-/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD-"] = -1.0
# (+/+) vs NPM1+
limma_contrast.loc["Black_NPM1+/FLT3-ITD+", "Black_NPM1+/FLT3-ITD+_vs_Black_NPM1+/FLT3-ITD-"] = 1.0
limma_contrast.loc["Black_NPM1+/FLT3-ITD-", "Black_NPM1+/FLT3-ITD+_vs_Black_NPM1+/FLT3-ITD-"] = -1.0
limma_contrast.loc["White_NPM1+/FLT3-ITD+", "White_NPM1+/FLT3-ITD+_vs_White_NPM1+/FLT3-ITD-"] = 1.0
limma_contrast.loc["White_NPM1+/FLT3-ITD-", "White_NPM1+/FLT3-ITD+_vs_White_NPM1+/FLT3-ITD-"] = -1.0
# (+/+) vs FLT3-ITD+
limma_contrast.loc["Black_NPM1+/FLT3-ITD+", "Black_NPM1+/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD+"] = 1.0
limma_contrast.loc["Black_NPM1-/FLT3-ITD+", "Black_NPM1+/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD+"] = -1.0
limma_contrast.loc["White_NPM1+/FLT3-ITD+", "White_NPM1+/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD+"] = 1.0
limma_contrast.loc["White_NPM1-/FLT3-ITD+", "White_NPM1+/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD+"] = -1.0

limma_contrast

,Black_NPM1-/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-,Black_NPM1+/FLT3-ITD-_vs_Black_NPM1-/FLT3-ITD-,White_NPM1+/FLT3-ITD-_vs_White_NPM1-/FLT3-ITD-,Black_NPM1-/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD-,White_NPM1-/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD-,Black_NPM1+/FLT3-ITD+_vs_Black_NPM1+/FLT3-ITD-,White_NPM1+/FLT3-ITD+_vs_White_NPM1+/FLT3-ITD-,Black_NPM1+/FLT3-ITD+_vs_Black_NPM1-/FLT3-ITD+,White_NPM1+/FLT3-ITD+_vs_White_NPM1-/FLT3-ITD+
Black_NPM1+/FLT3-ITD+,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
Black_NPM1+/FLT3-ITD-,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0
Black_NPM1-/FLT3-ITD+,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0
Black_NPM1-/FLT3-ITD-,1.0,-1.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0
White_NPM1+/FLT3-ITD+,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
White_NPM1+/FLT3-ITD-,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0
White_NPM1-/FLT3-ITD+,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0
White_NPM1-/FLT3-ITD-,-1.0,0.0,-1.0,0.0,-1.0,0.0,0.0,0.0,0.0

In [13]:
# write all the limma inputs as parquet files
limma_design.to_parquet(os.path.join(LIMMA_DIR, "design.parquet"))
limma_contrast.to_parquet(os.path.join(LIMMA_DIR, "contrast.parquet"))